# Адреса:
# Приложение доступно по http://localhost:8080 (envoy прокси)
# Панели мониторинга http://localhost:5601 (opensearch dashboards, kibana)
# Управление пользователями http://localhost:8081 (keycloak)
# Управление пользователями http://localhost:8081 (keycloak)

services:

#  app:
#    image: nginx:1.27.4
#    depends_on:
#      - fluent-bit
#      - envoy
#    volumes:
#      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./volumes/nginx/html:/usr/share/nginx/html
#    logging:
#      driver: "fluentd"
#      options:
#        # куда посылать лог-сообщения, необходимо чтобы адрес
#        # совпадал с настройками плагина forward
#        fluentd-address: localhost:24224
#        # теги используются для маршрутизации лог-сообщений, тема
#        # маршрутизации будет рассмотрена ниже
#        tag: app.logs
  app-ktor:
    image: ads-second-hand-books-ktor:0.0.1
    ports:
      - "8080:8080"
    environment:
      DB_TYPE_PROD: "inmemory"
    depends_on:
      - fluent-bit
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]


  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit:4.0.0-amd64
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    environment:
      - opensearch_host=opensearch
      - opensearch_user=admin
      - opensearch_pass=adm-Password0
    volumes:
      - ./volumes/fluent-bit-etc/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./volumes/fluent-bit-etc/parsers.conf:/fluent-bit/etc/parsers.conf

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.19.1
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=adm-Password0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:2.19.1
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch

#  envoy:
#    image: envoyproxy/envoy:v1.29.0
#    volumes:
#      - ./volumes/envoy/envoy.yaml:/etc/envoy/envoy.yaml
#    ports:
#      - "8080:8080"
#    depends_on:
#      keycloak:
#        condition: service_healthy

#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0.4
#    volumes:
#      - ./volumes/keycloak/import:/opt/keycloak/data/import
#    environment:
#      KEYCLOAK_USER: otus
#      KEYCLOAK_PASSWORD: otus
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KEYCLOAK_IMPORT: "/tmp/realm-export.json"
#      KC_HEALTH_ENABLED: "true"
#      KC_HOSTNAME_URL: "http://localhost:8080/"
#    healthcheck:
#      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3" ]
#      interval: 10s
#      timeout: 5s
#      retries: 15
#    command:
#      - start-dev
#      - --hostname-port=8081
#      - --import-realm
#      - --proxy-headers=forwarded
#      - --hostname-strict=false

volumes:
  opensearch-data:
