ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "org.akira.otuskotlin.ads.app.ktor.ApplicationKt.module"
  logger: logback